apiVersion: v1
kind: ConfigMap
metadata:
  name: go-service-config
data:
  ENV: "prod"
  PORT: "8000"
  HOST: "0.0.0.0"
  PORT_FRONTEND: "https://example.com"
  POSTGRES_HOST: "postgresql"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
