apiVersion: v1
kind: Secret
metadata:
  name: go-service-secrets
type: Opaque
stringData:
  RANDOM_PASSWORD: "replace-with-secret-manager-value"
  CSRF_TOKEN: "replace-with-secret-manager-value"
  POSTGRES_DB: "app_db"
  POSTGRES_USER: "app_user"
  POSTGRES_PASSWORD: "replace-with-secret-manager-value"
  REDIS_USER: "default"
  REDIS_PASSWORD: ""
  RABBIT_USER: "app_user"
  RABBIT_PASSWORD: "replace-with-secret-manager-value"
  RABBIT_URL: "replace-with-secret-manager-value"
